### ISSUE TITLE
getX should error if no data to query

### ISSUE THREAD

**Issue by mellowdrifter** [mellowdrifter/python-bgpstuff.net#1]
example, getRoute() should update object error to state there is nothing to query

**Comment by mellowdrifter** [comment]
Actually this already works. I was going to throw an exception, but Python already throws an exception:

>>> import bgpstuff
>>> q = bgpstuff.Response()
>>> q.getRoute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mellowd/go/src/github.com/mellowdrifter/python-bgpstuff.net/bgpstuff.py", line 90, in getRoute
    if not self.ip:
  File "/home/mellowd/go/src/github.com/mellowdrifter/python-bgpstuff.net/bgpstuff.py", line 30, in ip
    return self._ip
AttributeError: 'Response' object has no attribute '_ip'
